Django-day3/bookStore/bookStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('books/', include('books.urls')),
    path("accounts/", include("django.contrib.auth.urls")),  # new
    
    path('auth/', include('auth_app.urls')),
    
]

Django-day3/bookStore/books/urls.py
from django.urls import path
from .views import index, book_list, book_detail, book_delete, book_update, book_add, book_edit

app_name = 'book'

# http://localhost:8000/post/2/comment/1
urlpatterns = [
    path('index', index, name='book-index'),
    path('book_list/', book_list, name="book-list"),
    path('book_add/', book_add, name="book-add"),
    
    path('book_detail/<int:book_id>', book_detail, name="book-detail"),
    
    path('book_delete/<int:book_id>', book_delete, name="book-delete"),
    path('book_edit/<int:book_id>', book_edit, name="book-edit"),
    
    path('book_update/<int:book_id>', book_update, name="book-update")
    
]

Django-day3/bookStore/home/urls.py
from django.urls import path
from .views import index


urlpatterns = [
    path('', index, name='home-index')
]

Django-day3/bookStore/books/models.py
import random
from xml.dom import ValidationErr
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name.strip()) < 2:
            raise forms.ValidationError(
                'The minimum length of a category name is 2 characters.')
        return name


class Review(models.Model):
    comment = models.TextField()
    book = models.ForeignKey("Book", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return '{} - Review '.format(self.book.title)


class Book(models.Model):

    title = models.CharField("Book title", max_length=255, unique=True)
    author = models.CharField("Book author", max_length=255, )
    description = models.TextField("Book Description")
    likes = models.IntegerField(default=0)
    watch_count = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    rate = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    categories = models.ManyToManyField(Category)
    isbn = models.OneToOneField(
        "ISBN", on_delete=models.CASCADE, null=True, blank=True)

    def clean(self):
        if len(self.title.strip()) < 10 or len(self.title.strip()) > 50:
            raise ValidationErr(
                'The length of a book title should be between 10 and 50 characters.')

    class Meta:
        permissions = [
            ('book_delete', 'Can delete posts'),
        ]


class ISBN(models.Model):
    author = models.CharField(max_length=255, null=True, blank=True)
    book_title = models.CharField(max_length=255, null=True, blank=True)
    number = models.CharField(
        max_length=13, unique=True, null=True, blank=True)

    def __str__(self):
        return self.number

    def save(self, *args, **kwargs):
        if not self.number:
            # Generate new ISBN number
            prefix = str(random.randint(100, 999))
            group_id = str(random.randint(10, 99))
            publisher_id = str(random.randint(10000, 99999))
            check_digit = str(random.randint(0, 9))
            self.number = f"{prefix}-{group_id}-{publisher_id}-{check_digit}"
        super().save(*args, **kwargs)

        class Meta:
            unique_together = ('book_title', 'number')

Django-day3/bookStore/books/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'description',
                  'likes', 'watch_count', 'price', 'rate')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'likes': forms.NumberInput(attrs={'class': 'form-control'}),
            'watch_count': forms.NumberInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'rate': forms.NumberInput(attrs={'class': 'form-control'}),
        }

Django-day3/bookStore/books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from .models import Book
from django.views.decorators.csrf import csrf_exempt
from .forms import BookForm
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.


def index(request):

    return render(request, 'main/base_layout.html')


def book_list(request):
    all_books = Book.objects.all()

    return render(request, 'book/book_list.html', context={"books": all_books})


@login_required(login_url='login')
def book_add(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            # Redirect to the book list page
            return redirect('book:book-list')
    else:
        form = BookForm()

    return render(request, 'book/book_add.html', context={'form': form})


def book_detail(request, *args, **kwrgs):
    book_id = kwrgs.get('book_id')
    book = Book.objects.get(pk=book_id)

    return render(request, 'book/book_details.html', context={"book": book})


@permission_required('books.delete_post')
def book_delete(request, **kwargs):
    book_id = kwargs.get('book_id')

    Book.objects.get(pk=book_id).delete()

    return redirect('book:book-list')


def book_edit(request, **kwargs):
    book_id = kwargs.get('book_id')
    book_object = _get_book(book_id)
    return render(request, 'book/book_edit.html', context=book_object)


def book_update(request, **kwargs):
    book_id = kwargs.get('book_id')
    book = Book.objects.get(pk=book_id)

    form = BookForm(instance=book)
    if request.method == "PUT":
        form = BookForm(data=request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect("book:book-detail", pk=book.id)

    return redirect('book:book-list', context={
        'form': form,
        'book': book
    })

Django-day3/bookStore/books/templates/book/book_add.html
{% extends 'main/base_layout.html' %} {% block main-content %} {% comment %}
<div class="container mx-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title bg-success py-2 text-center">Add New Book</h1>
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="ISBN">ISBN</label>
              <input
                type="text"
                class="form-control"
                id="ISBN"
                name="ISBN"
                required
              />
            </div>
            <div class="form-group">
              <label for="title">Title</label>
              <input
                type="text"
                class="form-control"
                id="title"
                name="title"
                required
              />
            </div>
            <div class="form-group">
              <label for="author">Author</label>
              <input
                type="text"
                class="form-control"
                id="author"
                name="author"
                required
              />
            </div>
            <div class="form-group">
              <label for="publisher">Publisher</label>
              <input
                type="text"
                class="form-control"
                id="publisher"
                name="publisher"
                required
              />
            </div>
            <div class="form-group">
              <label for="price">Price</label>
              <input
                type="number"
                class="form-control"
                id="price"
                name="price"
                min="0"
                step=".01"
                required
              />
            </div>
            <div class="form-group">
              <label for="description">Description</label>
              <textarea
                class="form-control"
                id="description"
                name="description"
                rows="3"
              ></textarea>
            </div>
            <button type="submit" class="btn btn-primary my-2">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endcomment %}
<div class="container mx-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title bg-success py-2 text-center">
            Create New Book
          </h1>
          <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save New Book</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Django-day3/bookStore/books/templates/book/book_details.html
{% extends 'main/base_layout.html' %}


{% block main-content %}

  	<div class="container">
  <div class="row card my-2">
    <div class="col-md-6">
      <h1>{{ book.title }}</h1>
      <p>Author: {{ book.author }}</p>
      <p>Description: {{ book.description }}</p>
      <p>Likes: {{ book.likes }}</p>
      <p>Watch Count: {{ book.watch_count }}</p>
      <p>Price: {{ book.price }}</p>
      <p>Rate: {{ book.rate }}</p>
    </div>
  </div>
</div>

 <a class="btn btn-primary"  href="{% url 'book:book-list' %}"> Back to List</a>
{% endblock %}

Django-day3/bookStore/books/templates/book/book_edit.html
{% extends 'main/base_layout.html' %}


{% block main-content %}
	<div class="container mx-5">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<div class="card-body">
						<h1 class="card-title bg-success py-2 text-center ">Edit New Book</h1>
						<form method="POST">
							{% csrf_token %}
							<div class="form-group">
								<label for="ISBN">ISBN</label>
								<input type="text" class="form-control" id="ISBN" name="ISBN" required value={{ISBN}}>
							</div>
							<div class="form-group">
								<label for="title">Title</label>
								<input type="text" class="form-control" id="title" name="title" required value={{title}}>
							</div>
							<div class="form-group">
								<label for="author">Author</label>
								<input type="text" class="form-control" id="author" name="author" required value={{author}}>
							</div>
							<div class="form-group">
								<label for="publisher">Publisher</label>
								<input type="text" class="form-control" id="publisher" name="publisher" required value={{publisher}}>
							</div>
							<div class="form-group">
								<label for="price">Price</label>
								<input type="number" class="form-control" id="price" name="price" min="0" step=".01" required value={{price}}>
							</div>
							<div class="form-group">
								<label for="description">Description</label>
								<textarea class="form-control" id="description" name="description" rows="3">{{description}}</textarea>
							</div>
							<button type="submit" class="btn btn-primary my-2">Update</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>



    
{% endblock %}

Django-day3/bookStore/books/templates/book/book_list.html
{% extends 'main/base_layout.html' %} 
{# override block title #} 
{% block title%}
 book list
  {% endblock %} 
  {# override body #}
   {% block main-content %}
<a class="btn btn-primary" href="{% url 'book:book-add' %}"> Add New Book</a>
<table class="table table-condensed">
  <thead>
    <tr>
      <td>ISBN</td>
      <td>title</td>
      <td>description</td>
      <td>author</td>
      <td>likes</td>
      <td>Rates</td>

      <td>price</td>
      <td>Actions</td>

    </tr>
  </thead>

  <tbody>
    {% for book in books%}
    <tr>
      <td>{{ book.id }}</td>
      <td>{{ book.title }}</td>
      <td>{{ book.description | truncatewords:2 | title }}</td>
      <td>{{ book.author }}</td>
      <td>{{ book.likes }}</td>
      <td>{{ book.rate }}</td>

      <td>{{ book.price }}</td>
      


      <td>

      <a class="btn btn-info" href="{% url 'book:book-detail' book.id %}">
          View</a
        > 

      <a class="btn btn-success" href="{% url 'book:book-update' book.id %}">
          Edit</a
        > 

        <a class="btn btn-danger" href="{% url 'book:book-delete' book.id %}">
          Delete</a
        > 

      </td>
    </tr>

    {% empty %}
    <tr>
      <td colspan="5" class="text-center">sorry, not book in list</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}